name: build script for ctest.c		

on:							
  push:
    branches: [ "main" ]			

jobs:
  test:						
    runs-on: ubuntu-latest			
    steps:
      - uses: actions/checkout@v4		

      - name: build ctest			
        run: gcc -o ctest --coverage convert.c check.c usage.c help.c ProcessingNum.c ConvertNumToBase.c

      - name: upload binary			
        uses: actions/upload-artifact@v4	
        with:
          name: ctest			
          path: ./ctest

      - name: Run Tests
        run: ./test_script > test_results.txt

      - name: Upload Test Results
        if: ${{ always() }}

        uses: actions/upload-artifact@v4
        with:
          name: Test Results
          path: ./test_results.txt

     
      