name: build script for ctest.c		

on:							
  push:
    branches: [ "main" ]			

jobs:
  build:						
    runs-on: ubuntu-latest			
    steps:
      - uses: actions/checkout@v4		

      - name: build ctest			
        run: make ctest

      - name: upload binary			
        uses: actions/upload-artifact@v4	
        with:
          name: ctest			
          path: ./ctest

  test:						
    runs-on: ubuntu-latest			
    steps:
      - name: Run Tests
        run: make ctest
        run: ./test_script > test_results.txt

      - name: Upload Test Results
        if: ${{ always() }}

        uses: actions/upload-artifact@v4
        with:
          name: Test Results
          path: ./test_results.txt

     
      