name: build and test script for ctest.c		

on:							
  push:
    branches: [ "main" ]			

jobs:
  test:						
    runs-on: ubuntu-latest			
    steps:
      - uses: actions/checkout@v4		

      - name: Build ctest	and Run Tests		
        run: make ctest; ./test_script > test_results.txt; gcov ctest-convert.c; gcov ctest-check.c; gcov ctest-ConvertNumToBase.c; gcov ctest-ProcessingNum.c; gcov ctest-usage.c; gcov ctest-help.c

      - name: Upload Binary			
        uses: actions/upload-artifact@v4	
        with:
          name: ctest			
          path: ./ctest

      - name: Upload Test Results
        if: ${{ always() }}

        uses: actions/upload-artifact@v4
        with:
          name: Test Results
          path: ./test_results.txt

     
      